// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HeatmapCell represents a single populated cell in the activity heatmap.
 * Cells with zero visits are not returned -- the caller fills those in for rendering.
 */
export class HeatmapCell {
    /**
     * 0=Sunday through 6=Saturday, matches time.Weekday
     */
    "Day": number;

    /**
     * 0-23
     */
    "Hour": number;
    "TotalVisits": number;

    /** Creates a new HeatmapCell instance. */
    constructor($$source: Partial<HeatmapCell> = {}) {
        if (!("Day" in $$source)) {
            this["Day"] = 0;
        }
        if (!("Hour" in $$source)) {
            this["Hour"] = 0;
        }
        if (!("TotalVisits" in $$source)) {
            this["TotalVisits"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeatmapCell instance from a string or object.
     */
    static createFrom($$source: any = {}): HeatmapCell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeatmapCell($$parsedSource as Partial<HeatmapCell>);
    }
}
