// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DetectedSource represents a browser profile found on disk.
 * It is not yet saved to the database -- it is a candidate presented
 * to the user during onboarding or source management.
 */
export class DetectedSource {
    /**
     * e.g. "chrome" | "firefox" | "safari"
     */
    "Browser": string;

    /**
     * profile directory name or "default"
     */
    "Profile": string;

    /**
     * full path to the History or places.sqlite file
     */
    "Path": string;

    /**
     * human-readable suggestion e.g. "Chrome (Default)"
     */
    "Label": string;

    /**
     * engine family, derived from BrowserFamily(Browser)
     */
    "Family": Family;

    /** Creates a new DetectedSource instance. */
    constructor($$source: Partial<DetectedSource> = {}) {
        if (!("Browser" in $$source)) {
            this["Browser"] = "";
        }
        if (!("Profile" in $$source)) {
            this["Profile"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Family" in $$source)) {
            this["Family"] = Family.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedSource instance from a string or object.
     */
    static createFrom($$source: any = {}): DetectedSource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectedSource($$parsedSource as Partial<DetectedSource>);
    }
}

/**
 * Family identifies which browser engine a browser is based on.
 * Used by both discovery (for labeling) and ingestion (for dispatch).
 */
export enum Family {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FamilyChromium = "chromium",
    FamilyFirefox = "firefox",
    FamilySafari = "safari",
    FamilyUnknown = "unknown",
};
