// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SyncResult holds the outcome of a single source sync run.
 */
export class SyncResult {
    "SourceID": number;

    /**
     * rows successfully written
     */
    "NewVisits": number;

    /**
     * rows that failed normalization and were skipped
     */
    "Skipped": number;

    /**
     * non-nil = source-level failure, sync did not complete
     */
    "Error": any;

    /** Creates a new SyncResult instance. */
    constructor($$source: Partial<SyncResult> = {}) {
        if (!("SourceID" in $$source)) {
            this["SourceID"] = 0;
        }
        if (!("NewVisits" in $$source)) {
            this["NewVisits"] = 0;
        }
        if (!("Skipped" in $$source)) {
            this["Skipped"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResult($$parsedSource as Partial<SyncResult>);
    }
}
