// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as ingestion$0 from "../../../../zerebos/hindsight/internal/ingestion/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "sync:complete": ingestion$0.SyncResult;
            "sync:error": string;
            "sync:started": number;
        }
    }
}
