// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/generated/models.js";

/**
 * DashboardFilter holds the common time range and source filter
 * used across all dashboard queries. Zero values mean no filter.
 */
export class DashboardFilter {
    /**
     * unix ms, 0 = no lower bound
     */
    "StartTime": number;

    /**
     * unix ms, 0 = no upper bound
     */
    "EndTime": number;

    /** Creates a new DashboardFilter instance. */
    constructor($$source: Partial<DashboardFilter> = {}) {
        if (!("StartTime" in $$source)) {
            this["StartTime"] = 0;
        }
        if (!("EndTime" in $$source)) {
            this["EndTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): DashboardFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DashboardFilter($$parsedSource as Partial<DashboardFilter>);
    }
}

/**
 * DomainInsights summarizes domain discovery and diversity for a period.
 */
export class DomainInsights {
    /**
     * domains whose first-ever visit falls within the range
     */
    "NewDomains": number;

    /**
     * domains visited exactly once within the range
     */
    "OneOffDomains": number;

    /** Creates a new DomainInsights instance. */
    constructor($$source: Partial<DomainInsights> = {}) {
        if (!("NewDomains" in $$source)) {
            this["NewDomains"] = 0;
        }
        if (!("OneOffDomains" in $$source)) {
            this["OneOffDomains"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DomainInsights instance from a string or object.
     */
    static createFrom($$source: any = {}): DomainInsights {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DomainInsights($$parsedSource as Partial<DomainInsights>);
    }
}

/**
 * SearchParams holds all search and filter parameters for the query view.
 */
export class SearchParams {
    /**
     * full-text search across URL and title
     */
    "Text": string;

    /**
     * exact domain filter
     */
    "Domain": string;

    /**
     * unix ms, 0 = no lower bound
     */
    "StartTime": number;

    /**
     * unix ms, 0 = no upper bound
     */
    "EndTime": number;

    /**
     * "recent" (default) | "visits"
     */
    "SortBy": string;

    /**
     * 0-indexed
     */
    "Page": number;

    /**
     * defaults to 50 if 0
     */
    "PageSize": number;

    /** Creates a new SearchParams instance. */
    constructor($$source: Partial<SearchParams> = {}) {
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("Domain" in $$source)) {
            this["Domain"] = "";
        }
        if (!("StartTime" in $$source)) {
            this["StartTime"] = 0;
        }
        if (!("EndTime" in $$source)) {
            this["EndTime"] = 0;
        }
        if (!("SortBy" in $$source)) {
            this["SortBy"] = "";
        }
        if (!("Page" in $$source)) {
            this["Page"] = 0;
        }
        if (!("PageSize" in $$source)) {
            this["PageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchParams($$parsedSource as Partial<SearchParams>);
    }
}

/**
 * SearchResults holds a page of search results with total count for pagination.
 */
export class SearchResults {
    "Visits": db$0.SearchVisitsRow[];
    "Total": number;
    "Page": number;
    "PageSize": number;

    /** Creates a new SearchResults instance. */
    constructor($$source: Partial<SearchResults> = {}) {
        if (!("Visits" in $$source)) {
            this["Visits"] = [];
        }
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }
        if (!("Page" in $$source)) {
            this["Page"] = 0;
        }
        if (!("PageSize" in $$source)) {
            this["PageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResults instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResults {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Visits" in $$parsedSource) {
            $$parsedSource["Visits"] = $$createField0_0($$parsedSource["Visits"]);
        }
        return new SearchResults($$parsedSource as Partial<SearchResults>);
    }
}

/**
 * TimeSpent summarizes browsing time within the range. Duration coverage is
 * reported explicitly because not every browser records visit duration.
 */
export class TimeSpent {
    /**
     * total time across visits that report duration
     */
    "TotalDurationMs": number;

    /**
     * visits (visit_count weighted) that report duration
     */
    "VisitsWithDuration": number;

    /**
     * all visits in range, for coverage %
     */
    "TotalVisits": number;

    /**
     * most time-consuming domains, descending
     */
    "TopDomains": db$0.GetTopDomainsByDurationRow[];

    /** Creates a new TimeSpent instance. */
    constructor($$source: Partial<TimeSpent> = {}) {
        if (!("TotalDurationMs" in $$source)) {
            this["TotalDurationMs"] = 0;
        }
        if (!("VisitsWithDuration" in $$source)) {
            this["VisitsWithDuration"] = 0;
        }
        if (!("TotalVisits" in $$source)) {
            this["TotalVisits"] = 0;
        }
        if (!("TopDomains" in $$source)) {
            this["TopDomains"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeSpent instance from a string or object.
     */
    static createFrom($$source: any = {}): TimeSpent {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TopDomains" in $$parsedSource) {
            $$parsedSource["TopDomains"] = $$createField3_0($$parsedSource["TopDomains"]);
        }
        return new TimeSpent($$parsedSource as Partial<TimeSpent>);
    }
}

// Private type creation functions
const $$createType0 = db$0.SearchVisitsRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = db$0.GetTopDomainsByDurationRow.createFrom;
const $$createType3 = $Create.Array($$createType2);
