// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService exposes the search and query view to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "./internal/app/models.js";

export function SearchVisits(params: app$0.SearchParams): $CancellablePromise<app$0.SearchResults> {
    return $Call.ByID(4093448041, params).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = app$0.SearchResults.createFrom;
