// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes settings read/write to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetSettings(): $CancellablePromise<any> {
    return $Call.ByID(3034808949);
}

export function UpdateSettings(settings: any): $CancellablePromise<void> {
    return $Call.ByID(2846770304, settings);
}
