// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourceService exposes browser source management and sync to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as browser$0 from "./internal/browser/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/generated/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ingestion$0 from "./internal/ingestion/models.js";

export function DiscoverAndRegister(): $CancellablePromise<db$0.Source[]> {
    return $Call.ByID(1193093533).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DiscoverSources(): $CancellablePromise<browser$0.DetectedSource[]> {
    return $Call.ByID(1265746719).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetSources(): $CancellablePromise<db$0.Source[]> {
    return $Call.ByID(3957279378).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveSource(sourceID: number): $CancellablePromise<void> {
    return $Call.ByID(131466529, sourceID);
}

export function SyncAll(): $CancellablePromise<ingestion$0.SyncResult[]> {
    return $Call.ByID(4254658002).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SyncSource(sourceID: number): $CancellablePromise<ingestion$0.SyncResult> {
    return $Call.ByID(2435321250, sourceID).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = db$0.Source.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = browser$0.DetectedSource.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ingestion$0.SyncResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
