// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GeneralSettings {
    "LaunchAtLogin": boolean;
    "MinimizeToTray": boolean;

    /**
     * "system" | "light" | "dark"
     */
    "Theme": string;

    /** Creates a new GeneralSettings instance. */
    constructor($$source: Partial<GeneralSettings> = {}) {
        if (!("LaunchAtLogin" in $$source)) {
            this["LaunchAtLogin"] = false;
        }
        if (!("MinimizeToTray" in $$source)) {
            this["MinimizeToTray"] = false;
        }
        if (!("Theme" in $$source)) {
            this["Theme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneralSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneralSettings($$parsedSource as Partial<GeneralSettings>);
    }
}

/**
 * Settings mirrors the structure of config.toml.
 */
export class Settings {
    "General": GeneralSettings;
    "Sync": SyncSettings;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("General" in $$source)) {
            this["General"] = (new GeneralSettings());
        }
        if (!("Sync" in $$source)) {
            this["Sync"] = (new SyncSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("General" in $$parsedSource) {
            $$parsedSource["General"] = $$createField0_0($$parsedSource["General"]);
        }
        if ("Sync" in $$parsedSource) {
            $$parsedSource["Sync"] = $$createField1_0($$parsedSource["Sync"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class SyncSettings {
    /**
     * 0 = manual only
     */
    "IntervalMinutes": number;
    "SyncOnLaunch": boolean;
    "SyncOnWake": boolean;

    /** Creates a new SyncSettings instance. */
    constructor($$source: Partial<SyncSettings> = {}) {
        if (!("IntervalMinutes" in $$source)) {
            this["IntervalMinutes"] = 0;
        }
        if (!("SyncOnLaunch" in $$source)) {
            this["SyncOnLaunch"] = false;
        }
        if (!("SyncOnWake" in $$source)) {
            this["SyncOnWake"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncSettings($$parsedSource as Partial<SyncSettings>);
    }
}

// Private type creation functions
const $$createType0 = GeneralSettings.createFrom;
const $$createType1 = SyncSettings.createFrom;
